# ベースイメージとしてPython公式イメージを使用
FROM python:3.8

# 環境変数を設定
ENV PYTHONUNBUFFERED 1

# ワークディレクトリを作成
RUN mkdir /code

# ワークディレクトリを指定
WORKDIR /code

# requirements.txtをコピーし、パッケージをインストール
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# プロジェクトファイルをコピー
COPY . /code/