version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: ./mypage
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mypage:/code
    ports:
      - '8000:8000'
    depends_on:
      - db