# ベースイメージを指定
FROM ubuntu:22.04

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    python3.9 \
    python3-pip \
    mysql-client \
    libmysqlclient-dev \
    pkg-config \
    mysql-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# ホストOSのrequirements.txtファイルを実行ディレクトリにコピー
COPY requirements.txt ./

# requirements.txt記載のパッケージをインストール
RUN pip install -r requirements.txt

# MySQLのインストールと設定
#RUN /usr/bin/mysqld_safe --skip-grant-tables &
#RUN sleep 5
#RUN mysql -e "CREATE DATABASE mydatabase;" && \
#    mysql -e "CREATE USER 'myuser'@'%' IDENTIFIED BY 'mypassword';" && \
#    mysql -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%';" && \
#    mysql -e "FLUSH PRIVILEGES;"

# Djangoプロジェクトをコピー
COPY . /usr/src/app

# 開放するポートを指定
EXPOSE 8001


