# Generated by Django 4.2 on 2024-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('image1', models.ImageField(upload_to='photo1', verbose_name='イメージ画像1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photo1', verbose_name='イメージ画像2')),
                ('category', models.CharField(choices=[('TECH SKILL', 'tehSkill'), ('サッカー・フットサル', 'soccer_footsal'), ('登山', 'climb'), ('食事', 'food')], max_length=50, verbose_name='カテゴリ')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
